{% set version = "2018.12.03" %}
{% set name = "certifi" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/JohnAdders/python-{{ name }}/archive/{{ version }}.tar.gz
  sha256: b19516d6e0617ee2b36f333136bdc474fd62d2eb3cba4bee7bb23290b24fb357




 
build:
  noarch: python
  number: 1000
  preserve_egg_dir: True
  script: python setup.py install

requirements:
  host:
    - python
  run:
    - python

test:
  imports:
    - certifi

about:
  home: http://certifi.io/
  license: ISC
  license_file: LICENSE
  summary: Python package for providing Mozilla's CA Bundle.
  description: |
   Certifi is a curated collection of Root Certificates for validating the
   trustworthiness of SSL certificates while verifying the identity of TLS
   hosts.
  doc_url: https://pypi.python.org/pypi/certifi
  dev_url: https://github.com/JohnAdders/python-certifi
  doc_source_url: https://github.com/certifi/certifi.io/blob/master/README.rst

extra:
  recipe-maintainers:
    - johnad
