travis:
  secure:
    BINSTAR_TOKEN: k78JHer3/ckllDlMhsGs2itSsDgUAfv3CWVbqHdfYb0ZSHHzUSGzZ7cBh6frjY+KDGGbt4bKmplXxXT7EfpH7086TFIdOdMZYE94ZM9XWFakMuy/iAFXK2d46/YndP7rXj/V2Z3PhOQ4O3yBAhvpYTwwNbgAbn3XvmG3qkiiFxTepmKG8SoAtFaAf7AMwSph1BHjCrVly0BMq0JxlRv+bEk1H4VftFblHsAD81eqMLbtO22o5/Vlj7L3LsJSLe6GGUQnT4WHSj3sDKhaz2yhcULxEGvonPAVpWlXpwJN4WagnISiONm7T7sbBYYpWbKzXp54Dg9Hyb6GC6C70LVFzyv1tG3xPqX91Aedrvidt/OQl6iqKjJZx72syvKXCGeSng674LSvH8Ta4+/tzU3mxQiAbUZy5mHNK+ucrAUIk/4nfPfOoU2gs6MBTdyN3Lp/sOORbGKR8QW74LaHMRdUDuiP0882y1rqNIiZLHXweUiy3j6WKWO5L3qt5eyZ9POdfrXssTFr1erD+YbO96QmVY0yBbrpKXPNJZUqpVD7XVzGoa0NqkP2QcsSZ6oR718m795eugZWNI57tSLMuz+dHqRe81r4HIBiTE1ClTE39RnstZisVo9oOostmoKUy12usPUMLneHysJyiDDb3Ws/tFGXqLaLq3vNJa0k1uhntZk=
appveyor:
  secure:
    BINSTAR_TOKEN: gf2aX8IL0c52Hzc/W2uQdJcDVAG9EQvDUsZn2smHi24/Ocd3xRIVU3VHQwjXAMx3
